// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using segundo_parcial.Context;

#nullable disable

namespace segundo_parcial.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241126021527_counter")]
    partial class counter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("segundo_parcial.Model.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("segundo_parcial.Model.HistorialCrediticio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MontoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Rnc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HistorialCrediticios");
                });

            modelBuilder.Entity("segundo_parcial.Model.IndiceInflacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("IndInflacion")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IndiceInflaciones");
                });

            modelBuilder.Entity("segundo_parcial.Model.SaludFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Indicador")
                        .HasColumnType("text");

                    b.Property<int>("MontoTotalAdeudado")
                        .HasColumnType("integer");

                    b.Property<string>("Rnc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaludFinancieras");
                });

            modelBuilder.Entity("segundo_parcial.Model.TasaCambiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tasa")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TasaCambiarias");
                });
#pragma warning restore 612, 618
        }
    }
}
